export const IPC_SEARCH = 'IPC_SEARCH';
export const IPC_SEARCH_REPLY = 'IPC_SEARCH_REPLY';
export const IPC_RELOAD_WEB_CONTENT = 'IPC_RELOAD_WEB_CONTENT';
export const IPC_EXECUTE = 'IPC_EXECUTE';
export const IPC_SEARCH_COLLAPSE_WINDOW = 'IPC_SEARCH_COLLAPSE_WINDOW';
export const IPC_SEARCH_EXPAND_WINDOW = 'IPC_SEARCH_EXPAND_WINDOW';
